name: Quantum Kube CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install qiskit qiskit-ibm-runtime fastapi uvicorn pytest httpx

    - name: Run Unit Tests
      # This ensures your quantum logic works before we even think about K8s
      run: |
        # We'll create this test file in the next step
        PYTHONPATH=. pytest tests/

    - name: Set up Minikube
      # This starts a "Virtual" Kubernetes cluster inside the GitHub Runner
      uses: medyagh/setup-minikube@master
      with:
        container-runtime: docker
        # We enable the metrics-server here too, just like you did locally!
        addons: metrics-server

    - name: Build and Load Docker Image
      run: |
        docker build -t quantum-kube-app:test .
        minikube image load quantum-kube-app:test
        docker build -t quantum-kube-app:v1 .
        minikube image load quantum-kube-app:v1

    - name: Deploy to Minikube
      env:
        # This securely pulls the secret from GitHub's encrypted vault
        SUPER_SECRET_TOKEN: ${{ secrets.IBM_QUANTUM_TOKEN }}
      run: |
        # Create the K8s secret using the Environment Variable
        kubectl create secret generic quantum-api-key --from-literal=IBM_TOKEN=$SUPER_SECRET_TOKEN
        
        # Swaps 'v1' for 'test' in your YAML before applying it
        sed -i 's/quantum-kube-app:v1/quantum-kube-app:test/g' argo-templates/quantum-app.yaml
        sed -i 's/imagePullPolicy: Never/imagePullPolicy: IfNotPresent/g' argo-templates/quantum-app.yaml
        
        # Apply your existing infrastructure
        kubectl apply -f argo-templates/quantum-app.yaml
        
        # Wait for the heavy Qiskit pod to initialize
        kubectl rollout status deployment/quantum-gate-provider --timeout=180s
        
    - name: Debug Failure
      if: failure()
      run: |
        echo "Listing all pods..."
        kubectl get pods
        echo "Detailed description of the first pod..."
        kubectl describe pod -l app=quantum-api
        echo "Checking cluster events..."
        kubectl get events --sort-by='.metadata.creationTimestamp'

    - name: Integration Test
      run: |
        # Verify the API is actually responding inside the cluster
        kubectl get pods
        # We can use 'kubectl exec' to test the internal endpoint
        kubectl exec deployment/quantum-gate-provider -- curl -s http://localhost:8080/